export const CREATE_BOOK = 'CREATE_BOOK';
export const ACTIVE_MENU = 'ACTIVE_MENU';
export const RESIZE_SCREEN = 'RESIZE_SCREEN';
export const FETCH_ALL_DATES = 'FETCH_ALL_DATES';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';
export const FETCH_ANNOUNCEMENT = 'FETCH_ANNOUNCEMENT';
export const CLOSE_ANNOUNCEMENT = 'CLOSE_ANNOUNCEMENT';

export const START_PROCESSING = 'START_PROCESSING';
export const END_PROCESSING = 'END_PROCESSING';