export const CREATE_BOOK = 'CREATE_BOOK';
export const ACTIVE_MENU = 'ACTIVE_MENU';
export const RESIZE_SCREEN = 'RESIZE_SCREEN';
export const FETCH_ALL_DATES = 'FETCH_ALL_DATES';
export const INITIAL_SETUP = 'INITIAL_SETUP';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_SHIFTS = 'FETCH_SHIFTS';
export const RESET = 'RESET';
export const DELETE = 'DELETE';
export const UPDATE_DATA = 'UPDATE_DATA';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CLOSE_TICKET = 'CLOSE_TICKET';
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';
export const FETCH_ANNOUNCEMENT = 'FETCH_ANNOUNCEMENT';
export const FETCH_ANNOUNCEMENT_FOR_ADMIN = 'FETCH_ANNOUNCEMENT_FOR_ADMIN';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';
export const CLOSE_ANNOUNCEMENT = 'CLOSE_ANNOUNCEMENT';

export const START_PROCESSING = 'START_PROCESSING';
export const END_PROCESSING = 'END_PROCESSING';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';